version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  h2:
    image: oscarfonts/h2
    ports:
      - "9092:9092"
    volumes:
      - h2_data:/opt/h2-data

volumes:
  h2_data: